spring:
  application:
    name: api-gateway

  datasource:
    url: jdbc:postgresql://localhost:5432/tms_auth_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

  cloud:
#    discovery:
#      enabled: true


    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: lib-mng
          uri: lb://LIB-MNG
          predicates:
              - Path=/lib/**
          filters:
            - RewritePath=/lib/(?<segment>.*), /${segment}
            - AuthenticationFilter

eureka:
  client:
    service-url:
      defaultZone: http://Ravish:password@localhost:8761/eureka/

server:
  port: 8083



